drop table if exists games;
drop table if exists playerattributes;
drop table if exists players;
drop table if exists results;
drop table if exists teams;

source step01.sql;
source step02.sql;
source step03.sql;
source step04.sql;
source step05.sql;
source step06.sql;
source step07.sql;
source step08.sql;
source step09.sql;
source step10.sql;
source step11.sql;
source step12.sql;
source step13.sql;
source step15.sql;
source step16.sql;
source step17.sql;
source step18.sql;
source step19.sql;
source step20.sql;
source step20.sql;
source step21.sql;
source step22.sql;
#source step24.sql;
#source step23.sql;

